### ISSUE TITLE
Add fullscreen mode

### ISSUE THREAD

**Issue by PhoenixIV** [t-hamano/custom-html-block-extension#63]
Would be handy to be able to pop out that small html editor into a fullscreen overlay. Do you know if it's possible?

**Comment by t-hamano** [comment]
Hi @PhoenixIV,

That's a good idea. I would consider implementing it in the future.

**Comment by t-hamano** [comment]
Supported in version 3.2.0

**Comment by PhoenixIV** [comment]
Cool! Can you tell me how to enable it? I cannot find a symbol or a setting.

**Comment by PhoenixIV** [comment]
Ahh, nevermind! I had to look into the code to notice it is the pen symbol. I was looking for that symbol you would often find bottom right in videos.

**Comment by PhoenixIV** [comment]
Maybe use one of these symbols? https://www.svgrepo.com/vectors/fullscreen/

I like this one:
![https://www.svgrepo.com/svg/447382/fullscreen-alt](https://user-images.githubusercontent.com/2091755/224492140-f17d42ef-4258-46a5-bccd-8d0ddc0dd96a.png)
https://www.svgrepo.com/svg/447382/fullscreen-alt

I think it is very intuitive. Just like the regular rectangle ones you see everywhere. And maybe change the label to "Open in fullscreen [editor]".

**Comment by t-hamano** [comment]
Thanks for the feedback.
I would like to use the [@wordpress/icons](https://www.npmjs.com/package/@wordpress/icons) package icon to be consistent with the block editor UI.

Here is the site where you can see all the icons of the `@wordpress/icons` package that I have independently published.
https://t-hamano.github.io/wordpress-icon-list/

I prefer the `fullscreen` icons the most, what do you think?

![fullscreen](https://user-images.githubusercontent.com/54422211/224519855-30056a5a-7ff8-4815-b9b9-755cabd7a24a.png)

**Comment by PhoenixIV** [comment]
Perfect.
