### ISSUE TITLE
Use browser's default monospace font?

### ISSUE THREAD

**Issue by rghedin** [t-hamano/custom-html-block-extension#67]
Hi! I'm really grateful for finding such a useful plugin! :)

A humble suggestion: would be possible to offer an option to select the default browser's monospace font instead of those “web fonts” (Fira Code, Source Code Pro etc.)?

**Comment by t-hamano** [comment]
I have included this feature in version 3.3.0. If `monospace` is selected in the font family dropdown, no web font is applied, only monospace as a CSS value.

I would like to close this issue, but if you have any problems, please submit a new issue.
