### ISSUE TITLE
Option to restrict plugin by role

### ISSUE THREAD

**Issue by antoniorodc** [t-hamano/custom-html-block-extension#69]
Hi,

First of all, congratulations for your plugin, it works very well.

An interesting option will be to restrict the loading of the plugin according to the user role. 

Regards

**Comment by antoniorodc** [comment]
Exactly

Thank you

**Comment by t-hamano** [comment]
I understand. I will consider implementing this in a future version.

**Comment by antoniorodc** [comment]
Great, thank you

**Comment by t-hamano** [comment]
Hi @antoniorodc,

I have included this feature in version 3.3.0. I would like to close this issue, but if you have any problems, please feel free to submit a new issue.
