### ISSUE TITLE
Conflict with Add cover image or image gallery to Woocommerce product

### ISSUE THREAD

**Issue by binvoyons** [t-hamano/custom-html-block-extension#85]
Hello! First of all, thank you very much for this plugin, which is very useful. I just wanted to let you know that the plugin prevents any media from being added to a Woocommerce product page. When the plugin is activated, clicking on the "Add media" button in the right-hand sidebar no longer opens the media gallery modal. When the plugin is deactivated, it works as expected.

Thanks a lot!

**Comment by t-hamano** [comment]
I am closing this issue because I cannot reproduce this problem. If you have a complete procedure to reproduce it, please comment.
